# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevName', models.CharField(max_length=20, verbose_name='\u8bbe\u5907\u540d\u79f0')),
                ('DevType', models.CharField(default='\u4ee5\u592a\u4ea4\u6362\u673a', max_length=20, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('SimIntro', models.TextField(verbose_name='\u63a5\u53e3\u548c\u7535\u6e90')),
                ('MAC', models.CharField(max_length=20, null=True)),
                ('IPV4', models.CharField(blank=True, max_length=20, null=True, verbose_name='IPV4\u8def\u7531\u5bb9\u91cf')),
                ('IPV6', models.CharField(blank=True, max_length=20, null=True, verbose_name='IPV6\u8def\u7531\u5bb9\u91cf')),
                ('ThroughPut', models.CharField(max_length=20, null=True, verbose_name='\u6574\u7cfb\u7edf\u4ea4\u6362\u5bb9\u91cf')),
                ('PacketForwarding', models.CharField(max_length=20, null=True, verbose_name='\u5305\u8f6c\u53d1\u7387')),
                ('Queue', models.IntegerField(default=8, verbose_name='\u961f\u5217\u6570')),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('LastEditTime', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
                ('Manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_standard', to=settings.AUTH_USER_MODEL, verbose_name='\u7ba1\u7406\u5458')),
            ],
            options={
                'verbose_name': '\u300a\u8bbe\u5907\u89c4\u683c\u300b',
                'verbose_name_plural': '\u8bbe\u5907\u89c4\u683c\u53c2\u6570',
            },
        ),
        migrations.CreateModel(
            name='TestPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestOrganization', models.CharField(max_length=20, verbose_name='\u6d4b\u8bd5\u673a\u6784')),
                ('TestUserName', models.CharField(max_length=20, verbose_name='\u6d4b\u8bd5\u4eba\u5458')),
                ('Tel', models.BigIntegerField(verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('Email', models.CharField(default=b' ', max_length=30, verbose_name='\u90ae\u7bb1')),
                ('SpecManager', models.CharField(default=b'', max_length=20, verbose_name='\u7ba1\u7406\u5458')),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('LastEditTime', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u300a\u673a\u6784\u5ba2\u6237\u300b',
                'verbose_name_plural': '\u6d4b\u8bd5\u673a\u6784\u5ba2\u6237',
            },
        ),
    ]
