# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevName', models.CharField(max_length=20, verbose_name='\u8bbe\u5907\u540d\u79f0')),
                ('DevType', models.CharField(default='\u4ee5\u592a\u4ea4\u6362\u673a', max_length=20, verbose_name='\u9ed8\u8ba4\u4ee5\u592a\u4ea4\u6362\u673a')),
                ('SimIntro', models.TextField(verbose_name='\u8bbe\u5907\u7684\u63a5\u53e3\u548c\u7535\u6e90\u7b80\u5355\u4ecb\u7ecd')),
                ('MAC', models.IntegerField()),
                ('IPV4', models.IntegerField()),
                ('IPV6', models.IntegerField()),
                ('ThroughPut', models.IntegerField()),
                ('PacketForwarding', models.IntegerField()),
                ('Queue', models.IntegerField()),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('LastEditTime', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u300a\u8bbe\u5907\u53c2\u6570\u8868\u300b',
                'verbose_name_plural': '\u8bbe\u5907\u89c4\u683c\u53c2\u6570',
            },
        ),
        migrations.CreateModel(
            name='DeviceTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TemVersion', models.IntegerField(default=2, verbose_name='\u7248\u672c')),
                ('TemType', models.CharField(default='\u4ee5\u592a\u4ea4\u6362\u673a', max_length=20, verbose_name='\u7c7b\u578b')),
                ('TemPath', models.CharField(max_length=20, null=True, verbose_name='\u6a21\u677f\u8def\u5f84')),
                ('TemManager', models.CharField(default=b' ', max_length=20, verbose_name='\u7ba1\u7406\u5458')),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('LastEditTime', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u300a\u5165\u7f51\u6a21\u677f\u300b',
                'verbose_name_plural': '\u5165\u7f51\u8bbe\u5907\u6a21\u677f',
            },
        ),
        migrations.CreateModel(
            name='TestPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestOrganization', models.CharField(max_length=20, verbose_name='\u6d4b\u8bd5\u673a\u6784')),
                ('TestUserName', models.CharField(max_length=20, verbose_name='\u6d4b\u8bd5\u4eba\u5458')),
                ('Tel', models.BigIntegerField(verbose_name='\u8054\u7cfb\u65b9\u5f0f')),
                ('Email', models.CharField(default=b' ', max_length=30, verbose_name='\u90ae\u7bb1')),
                ('SpecManager', models.CharField(default=b'', max_length=20, verbose_name='\u7ba1\u7406\u5458')),
                ('IsDelete', models.BooleanField(default=False)),
                ('CreateTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('LastEditTime', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u300a\u673a\u6784\u5ba2\u6237\u300b',
                'verbose_name_plural': '\u6d4b\u8bd5\u673a\u6784\u5ba2\u6237',
            },
        ),
    ]
