# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicespec',
            options={'verbose_name': '\u300a\u89c4\u683c\u53c2\u6570\u300b', 'verbose_name_plural': '\u8bbe\u5907\u89c4\u683c\u53c2\u6570'},
        ),
        migrations.RemoveField(
            model_name='devicespec',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='devicespec',
            name='SpecManager',
        ),
        migrations.RemoveField(
            model_name='devicespec',
            name='Tel',
        ),
        migrations.RemoveField(
            model_name='devicespec',
            name='TestOrganization',
        ),
        migrations.RemoveField(
            model_name='devicespec',
            name='TestUserName',
        ),
        migrations.AddField(
            model_name='devicespec',
            name='SpecPath',
            field=models.CharField(default='', max_length=30, verbose_name='\u89c4\u683c\u53c2\u6570\u6a21\u677f\u8def\u5f84'),
            preserve_default=False,
        ),
    ]
