# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20190416_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestandard',
            name='DevType',
            field=models.CharField(default='\u4ee5\u592a\u4ea4\u6362\u673a', max_length=20, verbose_name='\u8bbe\u5907\u7c7b\u578b'),
        ),
    ]
