# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_auto_20190416_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestandard',
            name='IPV4',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicestandard',
            name='IPV6',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicestandard',
            name='MAC',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicestandard',
            name='PacketForwarding',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='devicestandard',
            name='ThroughPut',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
