# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_auto_20190416_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestandard',
            name='IPV4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devicestandard',
            name='IPV6',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devicestandard',
            name='MAC',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devicestandard',
            name='PacketForwarding',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devicestandard',
            name='ThroughPut',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
