# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_auto_20190416_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicestandard',
            options={'verbose_name': '\u300a\u8bbe\u5907\u89c4\u683c\u300b', 'verbose_name_plural': '\u8bbe\u5907\u89c4\u683c\u53c2\u6570'},
        ),
    ]
