# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_auto_20190416_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestandard',
            name='IPV4',
            field=models.CharField(blank=True, default=b'\\', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devicestandard',
            name='IPV6',
            field=models.CharField(blank=True, default=b'\\', max_length=20, null=True),
        ),
    ]
